### ISSUE TITLE
Config come sottomodulo

### ISSUE THREAD

**Issue by lucat1** [csunibo/config-parser-go#2]
Io metterei la repo di config come sottomodulo.
Altrimenti, quando config viene aggiornato e ci sono delle breaking change, le repo che usano questo pacchetto devono aggiornare sia config che questo pacchetto, e assicurarsi che siano in sync.
Io la metterei come sottomodulo qua e direi che siamo a posto. Spero go supporti i sottomoduli di git, ma bisogna controllare.

**Comment by foxyseta** [comment]
Ah sì palese lo davo per scontato

**Comment by samuelemusiani** [comment]
Eh non credo che go supporti i sottomoduli. Cioè se importiamo questo in una repo non viene automaticamente preso config. Quindi anche se lo aggiungiamo come sottomodulo ho paura che siamo costretti ad avere due versione che devono essere in sync.

Forse c'è qualche tick per importare tutta questa repo come sottomodulo e usarla nei progetti go, in modo da includere anche config come sottomodulo annidato, però boh

**Comment by foxyseta** [comment]
Non ho trovato risposte in rete ma mi stupirei se tutti i moduli go esistenti fossero stati scritti senza usare sottomoduli git. Hai già fatto la prova? Io non ho go installato al momento.

**Comment by samuelemusiani** [comment]
Ho cercato anche io ma non trovo quasi nulla. Ho fatto qualche prova ma quando fai `go get` per aggiungerlo come dipendenza non clona i sottomoduli e non vedo nessuna flag per dirgli di farlo. Secondo me non è proprio possibile

**Comment by foxyseta** [comment]
Sad. Hai considerato anche aggiungere un file `.mod` a src/config e poi usarlo come modulo Go solo in config-parser-go (e non negli altri progetti?). D'altro canto già lo stiamo facendo quando importiamo i temi per Hugo, e quelli non hanno proprio nulla di codice Go. Per me ha senso perché se il sistema dei moduli Go non supporta l'integrazione con i sottomoduli git tanto vale usare i moduli Go uniformemente.

**Comment by samuelemusiani** [comment]
È possibile aggiungere un `go.mod` a config, però bisogna anche esportare un pacchetto e poi non hai modo di accedere ai file in modo comodo se non cercando a mano il loro path sul filesystem. Purtroppo go non ha le funzionalità per quello che vogliamo fare. Io rimarrei che abbiamo il parse e il modulo a parte nelle repo, stiamo semplicemente attenti di aggiornarli di conseguenza

**Comment by foxyseta** [comment]
okk ultimissima proposta e poi cedo se neanche questa ti piace. Mettere in `csunibo/config` un file `main.go` di tipo due righe con una sola funzione main che fa solo `os.Open(filepath)`. Così abbiamo un involucro minimale per go che non fa neanche parsing e apre solo il file.

>  Io rimarrei che abbiamo il parse e il modulo a parte nelle repo, stiamo semplicemente attenti di aggiornarli di conseguenza

Sto cercando in tutti i modi di evitare questa perché è accoppiamento fortissimo.

**Comment by samuelemusiani** [comment]
Purtroppo anche con il modulo sei costretto a cercare i file sul filesytem perché il percorso di esecuzione è realtivo al path dell'eseguibile principale e non del sottomodulo. È leggermente più pulito comunque rispetto ad avere solo il `go.mod` perché almeno nascondiamo tutta la parte di ricerca e la rendiamo disponibile a tutti quelli che includono la repo come dependency.

Le soluzioni sono due: la _prima_ consiste nel lasciare tutto come è adesso e quindi siamo costretti a stare attenti e aggiornare config e il parser in parallelo a mano; la _seconda_ invece sarebbe quella di creare un pacchetto go dentro config e utilizzarlo come dependency del parser che a sua volta viene usato come dependency dai progetti principali. Ci sono dei pro e dei contro ad entrambe le cose, sinceramente non so bene quale soluzione preferisco.

<ins>Prima soluzione</ins>:
**Pro**:
- Non dobbiamo fare nulla
- Evita di nascondere i file di config dentro il filesystem
- Evita di creare tantissime versioni minuscole di questo pacchetto che servirebbero soltanto per aggiornare config anche se il parser non cambia

**Contro**:
- Se non stiamo attenti un aggiornamento del sottomodulo config potrebbe rompere le applicazioni se non si aggiorna anche il parser


<ins>Seconda soluzione</ins>:
**Pro**:
- Una aggiornamento di config non può rompere le applicazioni perché dipendono tutte dal parser e finché non si aggiorna quello resta tutto intatto.

**Contro**:
- Nascondiamo sul filesystem i file. Per qualcuno che non sa come funziona il modulo è difficile trovarli.
- I file verrebbero salvati generalmente in `$HOME/go/pkg/mod/...` dove viene salvato il sorgente dei moduli, se si compila un'applicazione e poi si pulisce la cache dei moduli di go perdiamo anche i file della config
- Tutte le volte che si aggiorna la config siamo costretti ad avere una versione nuova di questo pacchetto
- Se in un futuro vogliamo fare un parser anche per altri linguaggi sporchiamo la repo della config con tanti file di linguaggi diversi

Sentirei anche altri cosa ne pensano (@lucat1). Vista la lista dei pro e dei contro sarei per la prima soluzione, però so quanto è facile che si rompa tutto molto facilmente. Non so bene quale scegliere, ci devo un po' pensare. Se avete altri pro e contro li aggiungo

**Comment by lucat1** [comment]
No no, non serve salvare il file in qualche percorso magico del filesystem, basta usare questo: https://pkg.go.dev/embed (che è built-in).
A quel punto, tutte le repo che dipendono sulla config aggiornano il pacchetto go e non succede nulla di shady. Aggiornamento manuale che avrebbero comunque dovuto fare (giustamente). Riceveremo una PR da dependabot in automatico su tutte le repo che dipendono su questa config.



> Se in un futuro vogliamo fare un parser anche per altri linguaggi sporchiamo la repo della config con tanti file di linguaggi diversi

Unico contro che rimane unaddressed per me è questo, ma non capisco bene quale sia il problema. Puoi fare un esempio?
